apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: c4p-service 
spec:
  template:
    metadata:
      annotations:  
        dapr.io/app-id: c4p-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "9092"
    spec:
      containers:
        - image: "{{ .Values.services.registry }}/{{ .Values.services.c4p.image }}:{{ .Values.services.tag  }}"
          env:
          - name: AGENDA_SERVICE_URL
            value: http://agenda-service.{{ .Release.Namespace }}.svc.cluster.local
          - name: NOTIFICATIONS_SERVICE_URL
            value: http://notifications-service.{{ .Release.Namespace }}.svc.cluster.local
          - name: PUBSUB_NAME
            value: {{ .Release.Name }}-conference-pubsub 
          - name: POSTGRES_HOST
            value: {{ .Release.Name }}-postgresql.default.svc.cluster.local
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: postgres-password    
          - name: POD_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName    

