apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        dapr.io/app-id: frontend
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "9092"
    spec:
      containers:
        - image: "{{ .Values.services.registry }}/{{ .Values.services.frontend.image }}:{{ .Values.services.tag  }}"
          env:
          - name: AGENDA_SERVICE_URL
            value: http://agenda-service.{{ .Release.Namespace }}.svc.cluster.local
          - name: C4P_SERVICE_URL
            value: http://c4p-service.{{ .Release.Namespace }}.svc.cluster.local
          - name: NOTIFICATIONS_SERVICE_URL
            value: http://notifications-service.{{ .Release.Namespace }}.svc.cluster.local  
          - name: PUBSUB_NAME
            value: {{ .Release.Name }}-conference-pubsub    
          - name: POD_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName    

