apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notifications-service 
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        dapr.io/app-id: notifications-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "9092"
    spec:
      containers:
        - image: "{{ .Values.services.registry }}/{{ .Values.services.notifications.image }}:{{ .Values.services.tag  }}"
          env:
          - name: PUBSUB_NAME
            value: {{ .Release.Name }}-conference-pubsub
          - name: POD_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName    

